name: persistent_bottom_nav_bar
description: A do all, highly customizable persistent/static bottom navigation bar for flutter.

homepage: https://github.com/ahmedmirza994/flutter_persistent_bottom_bar.git
repository: https://github.com/ahmedmirza994/flutter_persistent_bottom_bar.git
version: 2.0.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
